// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHTgVdKveHBzfj9byy2C0MnUaMcwF2Hoc',
    appId: '1:525998131227:web:648d42d5bcc4de1dc950be',
    messagingSenderId: '525998131227',
    projectId: 'cksigndemo',
    authDomain: 'cksigndemo.firebaseapp.com',
    storageBucket: 'cksigndemo.appspot.com',
    measurementId: 'G-ZXGS02FK87',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDd1LBIq7_iJkeeuaHuf8aDnFwiQpYPww',
    appId: '1:525998131227:android:2cd79e871c1b2a6ec950be',
    messagingSenderId: '525998131227',
    projectId: 'cksigndemo',
    storageBucket: 'cksigndemo.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBeJWvIwdG6wr14bMttwxI1VFnapHvQtfE',
    appId: '1:525998131227:ios:469147383ede7996c950be',
    messagingSenderId: '525998131227',
    projectId: 'cksigndemo',
    storageBucket: 'cksigndemo.appspot.com',
    iosBundleId: 'com.example.loginApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBeJWvIwdG6wr14bMttwxI1VFnapHvQtfE',
    appId: '1:525998131227:ios:e51522d66df9c9d6c950be',
    messagingSenderId: '525998131227',
    projectId: 'cksigndemo',
    storageBucket: 'cksigndemo.appspot.com',
    iosBundleId: 'com.example.loginApp.RunnerTests',
  );
}
